### ISSUE TITLE
Little bugs

### ISSUE THREAD

**Issue by jahirtrap** [Fuzss/aquaacrobatics#10]
- I have noticed that the moment the air runs out while in the water, the player takes damage much faster than normal.
- There is an animation bug when swimming when I use quark in my modpack, it's probably related to the change of armor rotations.

**Comment by Fuzss** [comment]
Are you using any specific items from Quark when the animation breaks? Armor rotations should be fixed as of v1.1.3.

**Comment by Fuzss** [comment]
Fixed in dd9fcd7 and released as v1.2 on CurseForge.
